blueprint:
  name: Multi-Area Switch Control Hue dimmer switch v0.4.3
  description: Control lights in multiple areas using ZHA Hue Dimmer switch with configurable brightness levels and transition time
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Switch
      selector:
        device:
          integration: zha
          manufacturer: Philips
    areas:
      name: Areas to Control
      description: Select one or more areas to control
      selector:
        area:
          multiple: true
    brightness_down:
      name: Down Button Brightness
      description: Brightness level when pressing down button
      default: 1
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1
    brightness_up:
      name: Up Button Brightness
      description: Brightness level when pressing up button
      default: 50
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1
    brightness_on:
      name: On Button Brightness
      description: Brightness level when pressing on button
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1
    transition_time:
      name: Transition Time
      description: Time in seconds to transition between brightness levels
      default: 1
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "seconds"
          mode: slider
          step: 0.1
    automation_scripts_for_off:
      name: Automations to Run on Double-Click off (Optional)
      description: Scripts to run when off button is double clicked
      default: []
      selector:
        entity:
          domain: script
          multiple: true
    
    automation_scripts_for_on:
      name: Automations to Run on Double-Click on (Optional)
      description: Scripts to run when on button is double clicked
      default: []
      selector:
        entity:
          domain: script
          multiple: true

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      cluster_id: 64512
      
action:
  - variables:
      command: '{{ trigger.event.data.command }}'
      
  - choose:
      # On button
      - conditions:
          - condition: template
            value_template: '{{ command == "on_press" }}'
        sequence:
          - service: light.turn_on
            target:
              area_id: !input areas
            data:
              brightness_pct: !input brightness_on
              transition: !input transition_time

      # Off button
      - conditions:
          - condition: template
            value_template: '{{ command == "off_press" }}'
        sequence:
          - service: light.turn_off
            target:
              area_id: !input areas
            data:
              transition: !input transition_time

      # Up button
      - conditions:
          - condition: template
            value_template: '{{ command == "up_press" }}'
        sequence:
          - service: light.turn_on
            target:
              area_id: !input areas
            data:
              brightness_pct: !input brightness_up
              transition: !input transition_time

      # Down button
      - conditions:
          - condition: template
            value_template: '{{ command == "down_press" }}'
        sequence:
          - service: light.turn_on
            target:
              area_id: !input areas
            data:
              brightness_pct: !input brightness_down
              transition: !input transition_time

      # Off double click (for scripts)
      - conditions:
          - condition: template
            value_template: '{{ command == "off_double_press" }}'
        sequence:
          - repeat:
              for_each: !input automation_scripts_for_off
              sequence:
                - service: script.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
      
      # On double click (for scripts)
      - conditions:
          - condition: template
            value_template: '{{ command == "on_double_press" }}'
        sequence:
          - repeat:
              for_each: !input automation_scripts_for_on
              sequence:
                - service: script.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"

mode: single