blueprint:
  name: Multi-Area Switch Control Hue dimmer switch v0.3.9
  description: Control lights in multiple areas using ZHA Hue Dimmer switch with discrete brightness levels
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Switch
      selector:
        device:
          integration: zha
          manufacturer: Philips
    areas:
      name: Areas to Control
      description: Select one or more areas to control
      selector:
        area:
          multiple: true
    light_entity:
      name: Primary Light
      description: Used to check light state for smart brightness control
      selector:
        entity:
          domain: light
    automation_scripts:
      name: Automations to Run on Double-Click (Optional)
      description: Scripts to run when off button is double clicked
      default: []
      selector:
        entity:
          domain: script
          multiple: true

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      cluster_id: 64512
      
action:
  - variables:
      command: '{{ trigger.event.data.command }}'
      
  - choose:
      # On button
      - conditions:
          - condition: template
            value_template: '{{ command == "on_press" }}'
        sequence:
          - service: light.turn_on
            target:
              area_id: !input areas
            data:
              brightness_pct: 100
              transition: 1

      # Off button
      - conditions:
          - condition: template
            value_template: '{{ command == "off_press" }}'
        sequence:
          - service: light.turn_off
            target:
              area_id: !input areas

      # Brightness Up
      - conditions:
          - condition: template
            value_template: '{{ command == "up_press" }}'
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input light_entity
                    state: 'off'
                sequence:
                  - service: light.turn_on
                    target:
                      area_id: !input areas
                    data:
                      brightness_pct: 1
            default:
              - service: light.turn_on
                target:
                  area_id: !input areas
                data:
                  brightness_pct: 50

      # Brightness Down
      - conditions:
          - condition: template
            value_template: '{{ command == "down_press" }}'
        sequence:
          - service: light.turn_on
            target:
              area_id: !input areas
            data:
              brightness_pct: 1

      # Off double click (for scripts)
      - conditions:
          - condition: template
            value_template: '{{ command == "off_double" }}'
        sequence:
          - repeat:
              for_each: !input automation_scripts
              sequence:
                - service: script.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"

mode: single